config/routes.rb
Rails.application.routes.draw do
  resources :chats
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "chats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @current_user = {id: 2, email: "indra@nineod.com"}
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:user_id, :receiver_id, :firebase_key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: chat, local: true) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :chat_user_id %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.number_field :receiver_id, id: :chat_receiver_id %>
  </div>

  <div class="field">
    <%= form.label :firebase_key %>
    <%= form.text_field :firebase_key, id: :chat_firebase_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Receiver</th>
      <th>Firebase key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.user_id %></td>
        <td><%= chat.receiver_id %></td>
        <td><%= chat.firebase_key %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @chat.user_id %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @chat.receiver_id %>
</p>

<p>
  <strong>Firebase key:</strong>
  <%= @chat.firebase_key %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>
 -->
<div id="root" style="height: 100%; position: relative;">
  <div class="layout" style="display: flex; flex-direction: column; height: 100%; flex-grow: 1; position: relative;">
    <!-- <div class="body" style=""> -->
      <!-- <div class="body_wrapper" style="position: absolute; top: 0; left: 0; bottom: 0; right: 0; height: 100%; display: flex; flex-direction: column; margin-right: 0;"> -->
        <!-- <div class="body-canvas" style="position: relative; flex-grow: 1;"> -->
          <div class="bodylist" style="overflow-x: auto; overflow-y: hidden; position: absolute; top: 0; bottom: 0;">
            <div class="lists" style="padding: 10px;height: 100%; display: inline-block;box-sizing: border-box; display: inline-flex;flex-direction: column;background-color: #dfe3e6;white-space: normal;">
<!-- <div class="container"> -->
  <!-- <h3 class=" text-center">Messaging</h3> -->
  <!-- <div class="messaging"> -->
    <!-- <div class="inbox_msg"> -->
      <!-- <div style="max-height: 8%"></div> -->
      <!-- <div class="mesgs"> -->
        <div style="position: relative;">
          <h2>21212</h2>
        </div>
        <div class="msg_history">
          <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
            <div class="received_msg">
              <div class="received_withd_msg">
                <p>Test which is a new approach to have all
                  solutions</p>
                <span class="time_date"> 11:01 AM    |    June 9</span></div>
            </div>
          </div>
          <div class="outgoing_msg">
            <div class="sent_msg">
              <p>Test which is a new approach to have all
                solutions</p>
              <span class="time_date"> 11:01 AM    |    June 9</span> </div>
          </div>
          <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
            <div class="received_msg">
              <div class="received_withd_msg">
                <p>Test, which is a new approach to have</p>
                <span class="time_date"> 11:01 AM    |    Yesterday</span></div>
            </div>
          </div>
          <div class="outgoing_msg">
            <div class="sent_msg">
              <p>Apollo University, Delhi, India Test</p>
              <span class="time_date"> 11:01 AM    |    Today</span> </div>
          </div>
          <div class="incoming_msg">
            <div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
            <div class="received_msg">
              <div class="received_withd_msg">
                <p>We work directly with our designers and suppliers,
                  and sell direct to you, which means quality, exclusive
                  products, at a price anyone can afford.</p>
                <span class="time_date"> 11:01 AM    |    Today</span></div>
            </div>
          </div>
        </div>
        <div class="type_msg">
          <div class="input_msg_write">
            <input type="text" class="write_msg" placeholder="Type a message" />
            <button class="msg_send_btn" type="button"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
          </div>
        </div>
      <!-- </div> -->
    <!-- </div> -->
    
    
    <!-- <p class="text-center top_spac"> Design by <a target="_blank" href="#">Sunil Rajput</a></p> -->
    
  <!-- </div> -->
<!-- </div> -->
            </div>
          </div>
        <!-- </div> -->
      <!-- </div> -->
    <!-- </div> -->
  </div>
</div>

<div id="message-form" data-firebase='<%= raw({ apiKey: ENV["firebase_apiKey"], authDomain: ENV["firebase_authDomain"], databaseURL: ENV["firebase_databaseURL"], projectId: ENV["firebase_projectId"], storageBucket: ENV["firebase_storageBucket"], messagingSenderId: ENV["firebase_messagingSenderId"] }.to_json) %>'>
  <% if true#!@chat_session.status.eql?('closed') %>
    <input id="value-msg"></input>
    <button id="adding">Add</button>
  <% end %>
</div>
<!-- <strong>Messages:</strong>
<div id="messages"></div>
 -->
<script>
  console.log('<%= raw({ apiKey: Rails.application.secrets.firebase_apiKey, authDomain: Rails.application.secrets.firebase_authDomain, databaseURL: Rails.application.secrets.firebase_databaseURL, projectId: Rails.application.secrets.firebase_projectId, storageBucket: Rails.application.secrets.firebase_storageBucket, messagingSenderId: Rails.application.secrets.firebase_messagingSenderId }.to_json) %>');
  console.log('<%= raw({ apiKey: ENV["firebase_apiKey"], authDomain: ENV["firebase_authDomain"], databaseURL: ENV["firebase_databaseURL"], projectId: ENV["firebase_projectId"], storageBucket: ENV["firebase_storageBucket"], messagingSenderId: ENV["firebase_messagingSenderId"] }.to_json) %>');
  function firebaseConfig() {
    var config = $('#message-form').data('firebase');
    return config
  }
  firebase.initializeApp(firebaseConfig());
  // signOut();

  var database = firebase.database();
  var refDb = database.ref('chats/job_request-11-10-903461171884c642d5f2/messages/')

  $('.msg_send_btn').on('click', function() {
    refDb.push({
      id: '<%= @current_user[:id] %>',
      name: '<%= @current_user[:email] %>',
      text: $('.write_msg').val(),
      time: "<%= Time.now.strftime('%D %H:%M:%S') %>",
      read: false
    })
  })

  const updateMessages = data => {
    console.log(data.val(), '<%= @current_user[:email] %>')
    var {id, name, text, time, read} = data.val()
    if (read) {
      read = '';
    } else {
      read = 'U';
    }

    if (id != '2') {
      // firebase.database().ref().child('<%#= @chat_session.provider_url %>/'+ data.key).update({read: true})
      // read = ''
    }

    let msgBlock = ''
    if (name == '<%= @current_user[:email] %>') {
      msgBlock += '<div class="outgoing_msg">';
      msgBlock += '<div class="sent_msg">';
      msgBlock += '<p>'+ text +'</p>';
      msgBlock += '<span class="time_date">'+ time +'</span> </div>';
      msgBlock += '</div>';
    } else {
      msgBlock += '<div class="incoming_msg">';
      msgBlock += '<div class="incoming_msg_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>';
      msgBlock += '<div class="received_msg">';
      msgBlock += '<div class="received_withd_msg">';
      msgBlock += '<p>'+ text +'</p>';
      msgBlock += '<span class="time_date">'+ time +'</span> </div>';
      msgBlock += '</div>';
      msgBlock += '</div>';
    };

    $('.msg_history').append(msgBlock)
    $('#value-msg').val('')
  }

  const changeStatus = data => {
    $('#'+ data.key +' .read_status').remove()
  }

  function signIn(email, password){
    firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
      var errorCode = error.code;
      var errorMessage = error.message;
      console.log(errorMessage)
      if (errorCode === "auth/user-not-found") {
        signUp(email, password)
      } else {
        alert(errorMessage)
      }
    });
  };
  function signUp(email, password){
    firebase.auth().createUserWithEmailAndPassword(email, password).catch(function(error) {
      var errorCode = error.code;
      var errorMessage = error.message;
      if (errorCode !== null || errorCode !== undefined) {
        alert(errorMessage)
      }
    })
  };
  function signOut(){
    firebase.auth().signOut()
  };

  refDb.on('child_added', updateMessages)
  refDb.on('child_changed', changeStatus)
  aa = []
  refDb.once('value', function(snapshot) {
    // console.log(snapshot.val())
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <head>
    <title>ChatWebApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet">
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>